// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TetGift.DAL.Context;

#nullable disable

namespace TetGift.DAL.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260129040845_AddDescriptionToYourEntity")]
    partial class AddDescriptionToYourEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "aal_level", new[] { "aal1", "aal2", "aal3" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "code_challenge_method", new[] { "s256", "plain" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "factor_status", new[] { "unverified", "verified" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "factor_type", new[] { "totp", "webauthn", "phone" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "oauth_authorization_status", new[] { "pending", "approved", "denied", "expired" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "oauth_client_type", new[] { "public", "confidential" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "oauth_registration_type", new[] { "dynamic", "manual" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "oauth_response_type", new[] { "code" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "one_time_token_type", new[] { "confirmation_token", "reauthentication_token", "recovery_token", "email_change_token_new", "email_change_token_current", "phone_change_token" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "realtime", "action", new[] { "INSERT", "UPDATE", "DELETE", "TRUNCATE", "ERROR" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "realtime", "equality_op", new[] { "eq", "neq", "lt", "lte", "gt", "gte", "in" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "storage", "buckettype", new[] { "STANDARD", "ANALYTICS", "VECTOR" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "extensions", "pg_stat_statements");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "extensions", "pgcrypto");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "extensions", "uuid-ossp");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "graphql", "pg_graphql");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vault", "supabase_vault");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TetGift.DAL.Entities.Account", b =>
                {
                    b.Property<int>("Accountid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("accountid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Accountid"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Fullname")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("fullname");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<DateTime?>("RegisterOtpExpiresAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("register_otp_expires_at");

                    b.Property<int>("RegisterOtpFailCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("register_otp_fail_count");

                    b.Property<string>("RegisterOtpHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("register_otp_hash");

                    b.Property<DateTime?>("RegisterOtpVerifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("register_otp_verified_at");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Accountid")
                        .HasName("account_pkey");

                    b.HasIndex(new[] { "Username" }, "account_username_key")
                        .IsUnique();

                    b.ToTable("account", (string)null);
                });

            modelBuilder.Entity("TetGift.DAL.Entities.Blog", b =>
                {
                    b.Property<int>("Blogid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("blogid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Blogid"));

                    b.Property<int?>("Accountid")
                        .HasColumnType("integer")
                        .HasColumnName("accountid");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("Creationdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creationdate")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool?>("Isdeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isdeleted");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Blogid")
                        .HasName("blog_pkey");

                    b.HasIndex("Accountid");

                    b.ToTable("blog", (string)null);
                });

            modelBuilder.Entity("TetGift.DAL.Entities.Cart", b =>
                {
                    b.Property<int>("Cartid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cartid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Cartid"));

                    b.Property<int?>("Accountid")
                        .HasColumnType("integer")
                        .HasColumnName("accountid");

                    b.Property<decimal?>("Totalprice")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("totalprice")
                        .HasDefaultValueSql("0");

                    b.HasKey("Cartid")
                        .HasName("cart_pkey");

                    b.HasIndex("Accountid");

                    b.ToTable("cart", (string)null);
                });

            modelBuilder.Entity("TetGift.DAL.Entities.CartDetail", b =>
                {
                    b.Property<int>("Cartdetailid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cartdetailid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Cartdetailid"));

                    b.Property<int?>("Cartid")
                        .HasColumnType("integer")
                        .HasColumnName("cartid");

                    b.Property<int?>("Productid")
                        .HasColumnType("integer")
                        .HasColumnName("productid");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Cartdetailid")
                        .HasName("cart_detail_pkey");

                    b.HasIndex("Cartid");

                    b.HasIndex("Productid");

                    b.ToTable("cart_detail", (string)null);
                });

            modelBuilder.Entity("TetGift.DAL.Entities.ConfigDetail", b =>
                {
                    b.Property<int>("Configdetailid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("configdetailid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Configdetailid"));

                    b.Property<int?>("Categoryid")
                        .HasColumnType("integer")
                        .HasColumnName("categoryid");

                    b.Property<int?>("Configid")
                        .HasColumnType("integer")
                        .HasColumnName("configid");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Configdetailid")
                        .HasName("config_detail_pkey");

                    b.HasIndex("Categoryid");

                    b.HasIndex("Configid");

                    b.ToTable("config_detail", (string)null);
                });

            modelBuilder.Entity("TetGift.DAL.Entities.Custom", b =>
                {
                    b.Property<int>("Customid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("customid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Customid"));

                    b.Property<string>("Greetingcardcontent")
                        .HasColumnType("text")
                        .HasColumnName("greetingcardcontent");

                    b.Property<string>("Greetingcardcustomurl")
                        .HasColumnType("text")
                        .HasColumnName("greetingcardcustomurl");

                    b.Property<string>("Greetingcardtemplate")
                        .HasColumnType("text")
                        .HasColumnName("greetingcardtemplate");

                    b.Property<string>("Logourl")
                        .HasColumnType("text")
                        .HasColumnName("logourl");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int?>("Orderdetailid")
                        .HasColumnType("integer")
                        .HasColumnName("orderdetailid");

                    b.HasKey("Customid")
                        .HasName("custom_pkey");

                    b.HasIndex("Orderdetailid");

                    b.ToTable("custom", (string)null);
                });

            modelBuilder.Entity("TetGift.DAL.Entities.Feedback", b =>
                {
                    b.Property<int>("Feedbackid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("feedbackid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Feedbackid"));

                    b.Property<int?>("Accountid")
                        .HasColumnType("integer")
                        .HasColumnName("accountid");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<bool?>("Isdeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isdeleted");

                    b.Property<int?>("Orderid")
                        .HasColumnType("integer")
                        .HasColumnName("orderid");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.HasKey("Feedbackid")
                        .HasName("feedback_pkey");

                    b.HasIndex("Accountid");

                    b.HasIndex("Orderid");

                    b.ToTable("feedback", (string)null);
                });

            modelBuilder.Entity("TetGift.DAL.Entities.Order", b =>
                {
                    b.Property<int>("Orderid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("orderid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Orderid"));

                    b.Property<int?>("Accountid")
                        .HasColumnType("integer")
                        .HasColumnName("accountid");

                    b.Property<string>("Customeraddress")
                        .HasColumnType("text")
                        .HasColumnName("customeraddress");

                    b.Property<string>("Customeremail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("customeremail");

                    b.Property<string>("Customername")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("customername");

                    b.Property<string>("Customerphone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("customerphone");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTime?>("Orderdatetime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("orderdatetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("Promotionid")
                        .HasColumnType("integer")
                        .HasColumnName("promotionid");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<decimal?>("Totalprice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("totalprice");

                    b.HasKey("Orderid")
                        .HasName("orders_pkey");

                    b.HasIndex("Accountid");

                    b.HasIndex("Promotionid");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("TetGift.DAL.Entities.OrderDetail", b =>
                {
                    b.Property<int>("Orderdetailid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("orderdetailid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Orderdetailid"));

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<int?>("Orderid")
                        .HasColumnType("integer")
                        .HasColumnName("orderid");

                    b.Property<int?>("Productid")
                        .HasColumnType("integer")
                        .HasColumnName("productid");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Orderdetailid")
                        .HasName("order_detail_pkey");

                    b.HasIndex("Orderid");

                    b.HasIndex("Productid");

                    b.ToTable("order_detail", (string)null);
                });

            modelBuilder.Entity("TetGift.DAL.Entities.Payment", b =>
                {
                    b.Property<int>("Paymentid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("paymentid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Paymentid"));

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<bool?>("Ispayonline")
                        .HasColumnType("boolean")
                        .HasColumnName("ispayonline");

                    b.Property<int?>("Orderid")
                        .HasColumnType("integer")
                        .HasColumnName("orderid");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Paymentid")
                        .HasName("payment_pkey");

                    b.HasIndex("Orderid");

                    b.ToTable("payment", (string)null);
                });

            modelBuilder.Entity("TetGift.DAL.Entities.Product", b =>
                {
                    b.Property<int>("Productid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("productid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Productid"));

                    b.Property<int?>("Accountid")
                        .HasColumnType("integer")
                        .HasColumnName("accountid");

                    b.Property<int?>("Categoryid")
                        .HasColumnType("integer")
                        .HasColumnName("categoryid");

                    b.Property<int?>("Configid")
                        .HasColumnType("integer")
                        .HasColumnName("configid");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("Productname")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("productname");

                    b.Property<string>("Sku")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sku");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<decimal?>("Unit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit");

                    b.HasKey("Productid")
                        .HasName("product_pkey");

                    b.HasIndex("Accountid");

                    b.HasIndex("Categoryid");

                    b.HasIndex("Configid");

                    b.ToTable("product", (string)null);
                });

            modelBuilder.Entity("TetGift.DAL.Entities.ProductCategory", b =>
                {
                    b.Property<int>("Categoryid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("categoryid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Categoryid"));

                    b.Property<string>("Categoryname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("categoryname");

                    b.Property<bool?>("Isdeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isdeleted");

                    b.HasKey("Categoryid")
                        .HasName("product_category_pkey");

                    b.ToTable("product_category", (string)null);
                });

            modelBuilder.Entity("TetGift.DAL.Entities.ProductConfig", b =>
                {
                    b.Property<int>("Configid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("configid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Configid"));

                    b.Property<string>("Configname")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("configname");

                    b.Property<string>("Imageurl")
                        .HasColumnType("text")
                        .HasColumnName("imageurl");

                    b.Property<bool?>("Isdeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isdeleted");

                    b.Property<string>("Suitablesuggestion")
                        .HasColumnType("text")
                        .HasColumnName("suitablesuggestion");

                    b.Property<decimal?>("Totalunit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("totalunit");

                    b.HasKey("Configid")
                        .HasName("product_config_pkey");

                    b.ToTable("product_config", (string)null);
                });

            modelBuilder.Entity("TetGift.DAL.Entities.ProductDetail", b =>
                {
                    b.Property<int>("Productdetailid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("productdetailid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Productdetailid"));

                    b.Property<int?>("Productid")
                        .HasColumnType("integer")
                        .HasColumnName("productid");

                    b.Property<int?>("Productparentid")
                        .HasColumnType("integer")
                        .HasColumnName("productparentid");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Productdetailid")
                        .HasName("product_detail_pkey");

                    b.HasIndex("Productid");

                    b.HasIndex("Productparentid");

                    b.ToTable("product_detail", (string)null);
                });

            modelBuilder.Entity("TetGift.DAL.Entities.Promotion", b =>
                {
                    b.Property<int>("Promotionid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("promotionid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Promotionid"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<decimal?>("Discountvalue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("discountvalue");

                    b.Property<DateTime?>("Expirydate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expirydate");

                    b.Property<bool?>("Isdeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isdeleted");

                    b.HasKey("Promotionid")
                        .HasName("promotion_pkey");

                    b.HasIndex(new[] { "Code" }, "promotion_code_key")
                        .IsUnique();

                    b.ToTable("promotion", (string)null);
                });

            modelBuilder.Entity("TetGift.DAL.Entities.Quotation", b =>
                {
                    b.Property<int>("Quotationid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("quotationid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Quotationid"));

                    b.Property<int?>("Accountid")
                        .HasColumnType("integer")
                        .HasColumnName("accountid");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Company")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("company");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int?>("Orderid")
                        .HasColumnType("integer")
                        .HasColumnName("orderid");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<DateTime?>("Requestdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("requestdate")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<decimal?>("Totalprice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("totalprice");

                    b.HasKey("Quotationid")
                        .HasName("quotation_pkey");

                    b.HasIndex("Accountid");

                    b.HasIndex("Orderid");

                    b.ToTable("quotation", (string)null);
                });

            modelBuilder.Entity("TetGift.DAL.Entities.QuotationFee", b =>
                {
                    b.Property<int>("Quotationfeeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("quotationfeeid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Quotationfeeid"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<short?>("Issubtracted")
                        .HasColumnType("smallint")
                        .HasColumnName("issubtracted");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<int?>("Quotationitemid")
                        .HasColumnType("integer")
                        .HasColumnName("quotationitemid");

                    b.HasKey("Quotationfeeid")
                        .HasName("quotation_fee_pkey");

                    b.HasIndex("Quotationitemid");

                    b.ToTable("quotation_fee", (string)null);
                });

            modelBuilder.Entity("TetGift.DAL.Entities.QuotationItem", b =>
                {
                    b.Property<int>("Quotationitemid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("quotationitemid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Quotationitemid"));

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<int?>("Productid")
                        .HasColumnType("integer")
                        .HasColumnName("productid");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int?>("Quotationid")
                        .HasColumnType("integer")
                        .HasColumnName("quotationid");

                    b.HasKey("Quotationitemid")
                        .HasName("quotation_item_pkey");

                    b.HasIndex("Productid");

                    b.HasIndex("Quotationid");

                    b.ToTable("quotation_item", (string)null);
                });

            modelBuilder.Entity("TetGift.DAL.Entities.Stock", b =>
                {
                    b.Property<int>("Stockid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("stockid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Stockid"));

                    b.Property<DateOnly?>("Expirydate")
                        .HasColumnType("date")
                        .HasColumnName("expirydate");

                    b.Property<DateTime?>("Lastupdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastupdated")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("Productid")
                        .HasColumnType("integer")
                        .HasColumnName("productid");

                    b.Property<DateOnly?>("Productiondate")
                        .HasColumnType("date")
                        .HasColumnName("productiondate");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<int?>("Stockquantity")
                        .HasColumnType("integer")
                        .HasColumnName("stockquantity");

                    b.HasKey("Stockid")
                        .HasName("stock_pkey");

                    b.HasIndex("Productid");

                    b.ToTable("stock", (string)null);
                });

            modelBuilder.Entity("TetGift.DAL.Entities.StockMovement", b =>
                {
                    b.Property<int>("Stockmovementid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("stockmovementid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Stockmovementid"));

                    b.Property<DateTime?>("Movementdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("movementdate")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int?>("Orderid")
                        .HasColumnType("integer")
                        .HasColumnName("orderid");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int?>("Stockid")
                        .HasColumnType("integer")
                        .HasColumnName("stockid");

                    b.HasKey("Stockmovementid")
                        .HasName("stock_movement_pkey");

                    b.HasIndex("Orderid");

                    b.HasIndex("Stockid");

                    b.ToTable("stock_movement", (string)null);
                });

            modelBuilder.Entity("TetGift.DAL.Entities.Blog", b =>
                {
                    b.HasOne("TetGift.DAL.Entities.Account", "Account")
                        .WithMany("Blogs")
                        .HasForeignKey("Accountid")
                        .HasConstraintName("blog_accountid_fkey");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("TetGift.DAL.Entities.Cart", b =>
                {
                    b.HasOne("TetGift.DAL.Entities.Account", "Account")
                        .WithMany("Carts")
                        .HasForeignKey("Accountid")
                        .HasConstraintName("cart_accountid_fkey");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("TetGift.DAL.Entities.CartDetail", b =>
                {
                    b.HasOne("TetGift.DAL.Entities.Cart", "Cart")
                        .WithMany("CartDetails")
                        .HasForeignKey("Cartid")
                        .HasConstraintName("cart_detail_cartid_fkey");

                    b.HasOne("TetGift.DAL.Entities.Product", "Product")
                        .WithMany("CartDetails")
                        .HasForeignKey("Productid")
                        .HasConstraintName("cart_detail_productid_fkey");

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TetGift.DAL.Entities.ConfigDetail", b =>
                {
                    b.HasOne("TetGift.DAL.Entities.ProductCategory", "Category")
                        .WithMany("ConfigDetails")
                        .HasForeignKey("Categoryid")
                        .HasConstraintName("config_detail_categoryid_fkey");

                    b.HasOne("TetGift.DAL.Entities.ProductConfig", "Config")
                        .WithMany("ConfigDetails")
                        .HasForeignKey("Configid")
                        .HasConstraintName("config_detail_configid_fkey");

                    b.Navigation("Category");

                    b.Navigation("Config");
                });

            modelBuilder.Entity("TetGift.DAL.Entities.Custom", b =>
                {
                    b.HasOne("TetGift.DAL.Entities.OrderDetail", "Orderdetail")
                        .WithMany("Customs")
                        .HasForeignKey("Orderdetailid")
                        .HasConstraintName("custom_orderdetailid_fkey");

                    b.Navigation("Orderdetail");
                });

            modelBuilder.Entity("TetGift.DAL.Entities.Feedback", b =>
                {
                    b.HasOne("TetGift.DAL.Entities.Account", "Account")
                        .WithMany("Feedbacks")
                        .HasForeignKey("Accountid")
                        .HasConstraintName("feedback_accountid_fkey");

                    b.HasOne("TetGift.DAL.Entities.Order", "Order")
                        .WithMany("Feedbacks")
                        .HasForeignKey("Orderid")
                        .HasConstraintName("feedback_orderid_fkey");

                    b.Navigation("Account");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("TetGift.DAL.Entities.Order", b =>
                {
                    b.HasOne("TetGift.DAL.Entities.Account", "Account")
                        .WithMany("Orders")
                        .HasForeignKey("Accountid")
                        .HasConstraintName("orders_accountid_fkey");

                    b.HasOne("TetGift.DAL.Entities.Promotion", "Promotion")
                        .WithMany("Orders")
                        .HasForeignKey("Promotionid")
                        .HasConstraintName("orders_promotionid_fkey");

                    b.Navigation("Account");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("TetGift.DAL.Entities.OrderDetail", b =>
                {
                    b.HasOne("TetGift.DAL.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("Orderid")
                        .HasConstraintName("order_detail_orderid_fkey");

                    b.HasOne("TetGift.DAL.Entities.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("Productid")
                        .HasConstraintName("order_detail_productid_fkey");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TetGift.DAL.Entities.Payment", b =>
                {
                    b.HasOne("TetGift.DAL.Entities.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("Orderid")
                        .HasConstraintName("payment_orderid_fkey");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("TetGift.DAL.Entities.Product", b =>
                {
                    b.HasOne("TetGift.DAL.Entities.Account", "Account")
                        .WithMany("Products")
                        .HasForeignKey("Accountid")
                        .HasConstraintName("product_accountid_fkey");

                    b.HasOne("TetGift.DAL.Entities.ProductCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("Categoryid")
                        .HasConstraintName("product_categoryid_fkey");

                    b.HasOne("TetGift.DAL.Entities.ProductConfig", "Config")
                        .WithMany("Products")
                        .HasForeignKey("Configid")
                        .HasConstraintName("product_configid_fkey");

                    b.Navigation("Account");

                    b.Navigation("Category");

                    b.Navigation("Config");
                });

            modelBuilder.Entity("TetGift.DAL.Entities.ProductDetail", b =>
                {
                    b.HasOne("TetGift.DAL.Entities.Product", "Product")
                        .WithMany("ProductDetailProducts")
                        .HasForeignKey("Productid")
                        .HasConstraintName("product_detail_productid_fkey");

                    b.HasOne("TetGift.DAL.Entities.Product", "Productparent")
                        .WithMany("ProductDetailProductparents")
                        .HasForeignKey("Productparentid")
                        .HasConstraintName("product_detail_productparentid_fkey");

                    b.Navigation("Product");

                    b.Navigation("Productparent");
                });

            modelBuilder.Entity("TetGift.DAL.Entities.Quotation", b =>
                {
                    b.HasOne("TetGift.DAL.Entities.Account", "Account")
                        .WithMany("Quotations")
                        .HasForeignKey("Accountid")
                        .HasConstraintName("quotation_accountid_fkey");

                    b.HasOne("TetGift.DAL.Entities.Order", "Order")
                        .WithMany("Quotations")
                        .HasForeignKey("Orderid")
                        .HasConstraintName("quotation_orderid_fkey");

                    b.Navigation("Account");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("TetGift.DAL.Entities.QuotationFee", b =>
                {
                    b.HasOne("TetGift.DAL.Entities.QuotationItem", "Quotationitem")
                        .WithMany("QuotationFees")
                        .HasForeignKey("Quotationitemid")
                        .HasConstraintName("quotation_fee_quotationitemid_fkey");

                    b.Navigation("Quotationitem");
                });

            modelBuilder.Entity("TetGift.DAL.Entities.QuotationItem", b =>
                {
                    b.HasOne("TetGift.DAL.Entities.Product", "Product")
                        .WithMany("QuotationItems")
                        .HasForeignKey("Productid")
                        .HasConstraintName("quotation_item_productid_fkey");

                    b.HasOne("TetGift.DAL.Entities.Quotation", "Quotation")
                        .WithMany("QuotationItems")
                        .HasForeignKey("Quotationid")
                        .HasConstraintName("quotation_item_quotationid_fkey");

                    b.Navigation("Product");

                    b.Navigation("Quotation");
                });

            modelBuilder.Entity("TetGift.DAL.Entities.Stock", b =>
                {
                    b.HasOne("TetGift.DAL.Entities.Product", "Product")
                        .WithMany("Stocks")
                        .HasForeignKey("Productid")
                        .HasConstraintName("stock_productid_fkey");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TetGift.DAL.Entities.StockMovement", b =>
                {
                    b.HasOne("TetGift.DAL.Entities.Order", "Order")
                        .WithMany("StockMovements")
                        .HasForeignKey("Orderid")
                        .HasConstraintName("stock_movement_orderid_fkey");

                    b.HasOne("TetGift.DAL.Entities.Stock", "Stock")
                        .WithMany("StockMovements")
                        .HasForeignKey("Stockid")
                        .HasConstraintName("stock_movement_stockid_fkey");

                    b.Navigation("Order");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("TetGift.DAL.Entities.Account", b =>
                {
                    b.Navigation("Blogs");

                    b.Navigation("Carts");

                    b.Navigation("Feedbacks");

                    b.Navigation("Orders");

                    b.Navigation("Products");

                    b.Navigation("Quotations");
                });

            modelBuilder.Entity("TetGift.DAL.Entities.Cart", b =>
                {
                    b.Navigation("CartDetails");
                });

            modelBuilder.Entity("TetGift.DAL.Entities.Order", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("OrderDetails");

                    b.Navigation("Payments");

                    b.Navigation("Quotations");

                    b.Navigation("StockMovements");
                });

            modelBuilder.Entity("TetGift.DAL.Entities.OrderDetail", b =>
                {
                    b.Navigation("Customs");
                });

            modelBuilder.Entity("TetGift.DAL.Entities.Product", b =>
                {
                    b.Navigation("CartDetails");

                    b.Navigation("OrderDetails");

                    b.Navigation("ProductDetailProductparents");

                    b.Navigation("ProductDetailProducts");

                    b.Navigation("QuotationItems");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("TetGift.DAL.Entities.ProductCategory", b =>
                {
                    b.Navigation("ConfigDetails");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("TetGift.DAL.Entities.ProductConfig", b =>
                {
                    b.Navigation("ConfigDetails");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("TetGift.DAL.Entities.Promotion", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("TetGift.DAL.Entities.Quotation", b =>
                {
                    b.Navigation("QuotationItems");
                });

            modelBuilder.Entity("TetGift.DAL.Entities.QuotationItem", b =>
                {
                    b.Navigation("QuotationFees");
                });

            modelBuilder.Entity("TetGift.DAL.Entities.Stock", b =>
                {
                    b.Navigation("StockMovements");
                });
#pragma warning restore 612, 618
        }
    }
}
